---
version: "3.8"
services:
    db_service:
        image: mongo:latest
        container_name: mongo
        ports:
          - "27017:27017"
        networks:
          - todo-network

    backend_service:
        image: todobackend:v1
        container_name: backendcont
        ports:
          - "5000:5000"
        networks:
          - todo-network
        depends_on:
          - db_service
        environment:
          MONGO_URI: mongodb://db_service:27017/todoapp
          JWT_SECRET: mysecretkey
          PORT: "5000"

    frontend_service:
        image: todofrontend:v1
        container_name: frontendcont
        ports:
          - "5173:5173"
        networks:
          - todo-network
        depends_on:
          - backend_service
networks:
  todo-network:
...        