apiVersion: batch/v1
kind: CronJob

metadata:
  name: hello-cronjob
  namespace: todons

spec:

  schedule: "*/1 * * * *"

  concurrencyPolicy: Forbid

  successfulJobsHistoryLimit: 2

  failedJobsHistoryLimit: 1

  jobTemplate:

    spec:

      template:

        spec:

          restartPolicy: OnFailure

          containers:

          - name: hello

            image: busybox

            command:
            - sh
            - -c
            - |
              echo "CronJob Started"
              date
              echo "CronJob Completed"
