apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: todons
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/todoapp?replicaSet=rs0"